remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 

title: "The Impact of Economic Activity and Urban Clustering Metrics on a State's Total Energy Sales"
description: "Exploring the socioeconomic and geographical impacts on electricity consumption."
