remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 

title: "Power Outages Analysis" # Replace with your desired title
description: "Exploring the socioeconomic and geographical impacts on electricity consumption."

author:
  - name: "Hana Ahmed"
    email: "hanahmed@umich.edu"
  - name: "Aditya Ashok"
    email: "ashoka@umich.edu"